### ISSUE TITLE
Valderingsklass behöver delas upp mer

### ISSUE THREAD

**Issue by Delph1** [Delph1/IK100G-H2627H24-Java-Project#9]
Funktionen emailKontroll behöver delas upp i två funktioner.

En som kollar om det som kommer in är tomt och en del som kollar om strängen är korrekt formaterad.

Psuedo något i stil med:

    funktion innehållernågot (sträng)
       test = email.getText().isEmpty())
       return test; 
    
    funktion epostkontroll(epostadress)
       if (!innehållernågot(epostadress)
           resultat = false;
       else
           resultat = regextest(epostadress)
       return resultat

**Comment by Fredrik-magnusson-uni** [comment]
Det är ordnat. Skapat lite snabbguide högst upp
